### ISSUE TITLE
why  separate tables per collection ?

### ISSUE THREAD

**Issue by giannik** [kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer#11]
May i ask why you are creating separate embedding tables per collection ?
why not a flat table like in sql lite provider that has one table for all the info ?
It looks like the sql server client  creates 3 parent child relational tables here.
Thank you.

**Comment by kbeaugrand** [comment]
> May i ask why you are creating separate embedding tables per collection ? why not a flat table like in sql lite provider that has one table for all the info ? It looks like the sql server client creates 3 parent child relational tables here. Thank you.

Hello @giannik and thank you for this question.

I was mostly inspired by PostgreSQL which also has dedicated tables per collection.

Unlike SQLite, I had to create a dedicated table to store the embeddings because the vector values are divided by rows (note that SQLite doesn't have a distance search function in place, it get all the rows in memory and calculate nearest in memory before returning them).

I also think we'll be able to get better performance in use since the embedding data will be partitioned by collection. This allows us to have smaller indexes to browse when we perform nearest match queries.

**Comment by giannik** [comment]
hmm, i figured it might have to do with performance after reading some articles too: 
https://www.architecture-performance.fr/ap_blog/semantic-vector-search-with-sql-server/
Thanks

**Comment by kbeaugrand** [comment]
Thanks for this article! I'll also look deeper on this one.

**Comment by kbeaugrand** [comment]
Thanks for this article! I'll also look deeper on this one.
