### ISSUE TITLE
Add the ability to specify default collection name

### ISSUE THREAD

**Issue by marcominerva** [kbeaugrand/SemanticKernel.Connectors.Memory.SqlServer#119]
When configuring SQL Server Memory for Kernel Memory, it could be useful to specify a default index, just we can do today for schema and table names.

**Comment by kbeaugrand** [comment]
@marcominerva , I think the default collection name is in fact provided by the Kernel Memory itself.
Before uploading a document (see: [https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Models/IndexExtensions.cs#L7](https://github.com/microsoft/kernel-memory/blob/main/service/Abstractions/Models/IndexExtensions.cs#L7)

I saw that I've added these lines during the index name normalization: 
```
        if (string.IsNullOrWhiteSpace(index))
        {
            index = Constants.DefaultIndex;
        }
```
But this is not relevant because I should not get any empty index name here because the KM is providing at least the default index name...

**Comment by marcominerva** [comment]
Yes, but I think it could be useful to have the ability to do something like this:

```
.WithSqlServerMemoryDb(new()
{
    ConnectionString = "...",
    DefaultIndex = "..."
})
```

So, if we want to use a different default index name, we don't have to repeat it for each `ImportAsync`, `SearchAsync` and `AskAsync` invocation.

By the way, I'm proposing this idea because there is a similar feature request for Qdrant: https://github.com/microsoft/kernel-memory/issues/285 and I think it could be useful for both scenarios.

**Comment by marcominerva** [comment]
This feature is on longer necessary because now the default index is handled at service level for all the storage engines (see https://github.com/microsoft/kernel-memory/pull/354).
